<?php

namespace PX500\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoStatRepository extends EntityRepository
{
}
