px500_core_homepage:
    path:     /hello/{name}
    defaults: { _controller: PX500CoreBundle:Default:index }

update:
    path:     /update
    defaults: { _controller: PX500CoreBundle:Default:update }

photos:
    path:     /photos
    defaults: { _controller: PX500CoreBundle:Default:listPhotos }

photo:
    path:     /photo/{uid}
    defaults: { _controller: PX500CoreBundle:Default:photo }
    requirements:
        uid: \d+

user:
    path:     /user/{username}
    defaults: { _controller: PX500CoreBundle:Default:photo }
    requirements:
        uid: \d+
