services:
#    px500_core.example:
#        class: PX500\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    service.data:
        class: PX500\CoreBundle\Services\DataService
        arguments: ["@doctrine.orm.entity_manager", %px_api_url%, %px_api_key%]